CASExample2/Controllers/DefaultController.cs
using System.Web.Mvc;

namespace CASExample2.Controllers
{
    public class DefaultController : Controller
    {
        // GET: Default
        public ActionResult Index()
        {
            return View();
        }
    }
}

CASExample2/Controllers/HomeController.cs
using System.Web.Mvc;

namespace CASExample2.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

CASExample2/Controllers/PublicController.cs
using System.Web.Mvc;

namespace CASExample2.Controllers
{
    public class PublicController : Controller
    {
        // GET: Public
        public ActionResult NotAuthorized()
        {
            return View();
        }
    }
}

CASExample2/Controllers/SecretController.cs
using DotNetCasClient;
using DotNetCasClient.Security;
using System.Web.Mvc;

// added this resource

namespace CASExample2.Controllers
{
    [Authorize] //will restrict controller method to users who meet the authemtication requirement; i.e. CAS
                //[Authorize(Roles = "admin")]
                /*Authorize will check that the user has been authenticated
                                             Roles will check if the user has the admin role
                                             Roles will call GetRolesForUser method in the CASExample2.App_Start.MyRoleProvider class
                                             */
    public class SecretController : Controller
    {
        // GET: Secret
        //[AllowAnonymous]
        public ActionResult Index()
        {
            //ViewBag.Message = "Your application description page.";
            //ICasPrincipal p = System.Web.HttpContext.Current.User;
            ICasPrincipal principal = CasAuthentication.CurrentPrincipal;
            ViewBag.Message = principal.Identity.Name; //System.Security.Principal.GenericIdentity
            return View();
        }
    }
}

CASExample2/Views/Default/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Public View</title>
</head>
<body>
    <div>
        This is Public View
    </div>
</body>
</html>

CASExample2/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

CASExample2/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

CASExample2/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>
<!-- Controller Actions -->
<div class="jumbotron" id="navigation">
    <ul>
        <li>
            <a href="@Url.Action("Index", "Default")" class="elements">
                <span>Default Page</span>
            </a>
        </li>
        <li>
            <a href="@Url.Action("Index", "Secret")" class="elements">
                <span>Secret Page</span>
            </a>
        </li>
    </ul>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

CASExample2/Views/Public/NotAuthorized.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>NotAuthorized</title>
</head>
<body>
    <div>
        You are not authorized to see the page you attempted to go to
    </div>
</body>
</html>

CASExample2/Views/Secret/Index.cshtml
@{
    Layout = null;

}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Secret</title>
</head>
<body>
    <div>
        This is a secret view
        <h3>@ViewBag.Message</h3>
    </div>
</body>
</html>

CASExample2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>